# Modelagem preditiva

A modelagem preditiva são modelos computacionais que usam a matemática para prever resultados futuros. Os algoritmos preditivos usam dados de treino para aprender sobre o comportamento das variáveis afim de buscar a aproximação da função alvo, a função alvo é a formulação matemática que explica a relação entre os dados de entrada e de saída.

A análise preditiva está sendo utilizada por empresas e indivíduos em todo o mundo para extrair valor de dados históricos, após ser desenvolvido e validado, o modelo preditivo consegue generalizar o conhecimento aprendido dos dados históricos para prever o futuro.

### Importando as bibliotecas necessárias

Para fazer nosso trabalho precisamos das funções e métodos por isso vamos importar as bibliotecas do python.

In [43]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import ExtraTreesRegressor
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score 

In [44]:
import warnings
warnings.filterwarnings('ignore')

### Carregando o conjunto de dados

In [45]:
# Carregando o conjunto de dados e salvando na variável 'imoveis'.
imoveis = pd.read_csv('../imoveis_clean_base.csv')

# Vamos tirar as colunas 'Unnamed: 0', 'Link', 'Estado', 'Cidade' e 'Descrição'
imoveis = imoveis.drop(['Unnamed: 0', 'Link', 'Estado', 'Cidade', 'Descrição'], axis=1)

In [46]:
pd.set_option('display.max_columns', 100)

# Verificando o dataset
imoveis.head()

Valor_aluguel  Valor_condomínio  Valor_iptu  Área_total  Qt_quartos  \
0         3250.0             700.0         0.0        75.0         3.0   
1         3100.0             856.0       290.0        60.0         2.0   
2         1500.0             280.0       160.0       110.0         3.0   
3         1300.0             399.0       100.0        60.0         2.0   
4         1100.0             360.0       110.0        95.0         3.0   

   Qt_vagas  Qt_banheiros  Academia  Acesso_para_deficientes  Ar_condicionado  \
0       2.0           2.0         0                        0                0   
1       2.0           2.0         1                        0                0   
2       2.0           3.0         0                        0                0   
3       1.0           2.0         1                        0                0   
4       2.0           1.0         0                        0                0   

   Área_de_serviço  Armário_embutido  Armário_na_cozinha  Bicicletário  \
0                0                 0                   0             0   
1                0                 0                   0             0   
2                1                 0                   0             0   
3                0                 0                   0             0   
4                0                 0                   0             0   

   Churrasqueira  Circuito_de_segurança  Conexão_à_internet  Elevador  \
0              0                      0                   0         1   
1              1                      0                   0         1   
2              0                      0                   0         0   
3              1                      0                   0         1   
4              0                      0                   0         0   

   Espaço_gourmet  Garagem  Interfone  Lavanderia  Mobiliado  Piscina  \
0               0        0          0           0          0        0   
1               1        0          0           0          0        1   
2               0        0          1           0          0        0   
3               1        0          0           0          0        1   
4               0        0          0           0          0        0   

   Playground  Quadra_de_tênis  Quadra_poliesportiva  Salão_de_festas  Sauna  \
0           0                0                     0                0      0   
1           0                0                     0                0      0   
2           0                0                     0                1      0   
3           0                0                     1                1      1   
4           0                0                     0                1      0   

   Segurança_24h  Sistema_de_alarme  Spa  Varanda  
0              0                  0    0        0  
1              0                  0    0        0  
2              0                  1    0        1  
3              0                  0    0        0  
4              0                  1    0        0

In [47]:
# Verificando a dimensão do nosso dataset
imoveis.shape

(15958, 33)

In [48]:
df = imoveis

In [49]:
# Separando a variável target
X = df.drop(['Valor_aluguel'], axis=1)
y = df['Valor_aluguel'].values

In [50]:
X

Valor_condomínio  Valor_iptu  Área_total  Qt_quartos  Qt_vagas  \
0                 700.0         0.0        75.0         3.0       2.0   
1                 856.0       290.0        60.0         2.0       2.0   
2                 280.0       160.0       110.0         3.0       2.0   
3                 399.0       100.0        60.0         2.0       1.0   
4                 360.0       110.0        95.0         3.0       2.0   
...                 ...         ...         ...         ...       ...   
15953             300.0        40.0        44.0         1.0       0.0   
15954             600.0         0.0        90.0         3.0       1.0   
15955            1200.0         0.0        52.0         2.0       1.0   
15956             350.0         0.0        35.0         1.0       1.0   
15957            1021.0         0.0        35.0         1.0       1.0   

       Qt_banheiros  Academia  Acesso_para_deficientes  Ar_condicionado  \
0               2.0         0                        0                0   
1               2.0         1                        0                0   
2               3.0         0                        0                0   
3               2.0         1                        0                0   
4               1.0         0                        0                0   
...             ...       ...                      ...              ...   
15953           1.0         0                        0                0   
15954           2.0         0                        0                0   
15955           2.0         0                        0                0   
15956           1.0         0                        0                0   
15957           1.0         0                        0                0   

       Área_de_serviço  Armário_embutido  Armário_na_cozinha  Bicicletário  \
0                    0                 0                   0             0   
1                    0                 0                   0             0   
2                    1                 0                   0             0   
3                    0                 0                   0             0   
4                    0                 0                   0             0   
...                ...               ...                 ...           ...   
15953                0                 0                   0             0   
15954                1                 0                   0             0   
15955                1                 0                   0             0   
15956                1                 0                   1             0   
15957                1                 0                   0             0   

       Churrasqueira  Circuito_de_segurança  Conexão_à_internet  Elevador  \
0                  0                      0                   0         1   
1                  1                      0                   0         1   
2                  0                      0                   0         0   
3                  1                      0                   0         1   
4                  0                      0                   0         0   
...              ...                    ...                 ...       ...   
15953              0                      1                   0         1   
15954              0                      0                   0         0   
15955              0                      0                   0         0   
15956              0                      0                   0         0   
15957              0                      0                   0         0   

       Espaço_gourmet  Garagem  Interfone  Lavanderia  Mobiliado  Piscina  \
0                   0        0          0           0          0        0   
1                   1        0          0           0          0        1   
2                   0        0          1           0          0        0   
3                   1        0          0           0      

In [51]:
y

array([3250., 3100., 1500., ..., 1600., 1000., 3500.])

### Padronização

In [52]:
scaler_X = StandardScaler().fit(X)
standardX = scaler_X.transform(X)

In [53]:
scaler_y = StandardScaler().fit(y.reshape(-1, 1))
standardy = scaler_y.transform(y.reshape(-1, 1))

In [54]:
standardX

array([[ 1.07379338, -0.82169789,  0.26097643, ..., -0.24833957,
        -0.14213381, -0.52139986],
       [ 1.59416898,  2.66063248, -0.37183549, ..., -0.24833957,
        -0.14213381, -0.52139986],
       [-0.32721784,  1.09958783,  1.73753757, ...,  4.02674446,
        -0.14213381,  1.91791382],
       ...,
       [ 2.74166389, -0.82169789, -0.70933518, ..., -0.24833957,
        -0.14213381,  1.91791382],
       [-0.09371597, -0.82169789, -1.42652202, ..., -0.24833957,
        -0.14213381, -0.52139986],
       [ 2.14456625, -0.82169789, -1.42652202, ..., -0.24833957,
        -0.14213381,  1.91791382]])

In [55]:
standardy

array([[ 1.82750174],
       [ 1.64627027],
       [-0.28686541],
       ...,
       [-0.16604443],
       [-0.89097031],
       [ 2.12955419]])

### Criando dados de treino e teste

In [56]:
# Separando dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(standardX, standardy, test_size=0.3, random_state=0)

### Vários modelos de regressão

Nessa parte vamos criar um array com vários algoritmos para executarmos ao mesmo tempo afim de ver os resultados.

In [57]:
# Preparando a lista de modelos
modelos = []
modelos.append(('LinearRegression', LinearRegression()))
modelos.append(('Ridge', Ridge()))
modelos.append(('Lasso', Lasso()))
modelos.append(('ElasticNet', ElasticNet()))
modelos.append(('KNN', KNeighborsRegressor()))
modelos.append(('DecisionTree', DecisionTreeRegressor()))
modelos.append(('RandomForest', RandomForestRegressor()))
modelos.append(('ExtraTrees', ExtraTreesRegressor()))
modelos.append(('XGB', XGBRegressor()))

Aplicando um loop for para executar em nossos dados de treino e teste todos os algoritmos.

In [58]:
mean = y.mean()
std = y.std()

In [61]:
for nome, modelo in modelos:
    
    model = modelo
    model.fit(X_train, y_train)
    result = model.predict(X_test)
    
    # Voltando com os valores reais sem a padronização
    y_test_rescaling = (y_test * std) + mean
    result_rescaling = (result * std) + mean
    
    R2 = r2_score(y_test_rescaling,result_rescaling)
    MAE = mean_absolute_error(y_test_rescaling,result_rescaling)
    
    msg = "%s: R^2 = %f | MAE = %f" % (nome, R2, MAE)
    print(msg)

LinearRegression: R^2 = 0.391366 | MAE = 504.122467
Ridge: R^2 = 0.391365 | MAE = 504.125076
Lasso: R^2 = -0.000107 | MAE = 679.952379
ElasticNet: R^2 = -0.000107 | MAE = 679.952379
KNN: R^2 = 0.417067 | MAE = 471.324060
DecisionTree: R^2 = 0.152962 | MAE = 552.150953
RandomForest: R^2 = 0.510800 | MAE = 430.662239
ExtraTrees: R^2 = 0.502296 | MAE = 428.645986
[09:44:19] WARNING: C:/Jenkins/workspace/xgboost-win64_release_0.90/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.
XGB: R^2 = 0.511451 | MAE = 447.419592


-------------------------------------------------

## Métricas de avaliação

### R-Quadrado (R²)

O R-Quadrado, ou Coeficiente de Determinação, é uma métrica que visa expressar a quantidade da variança dos dados que é explicada pelo modelo. Em outras palavras, essa medida calcula qual a porcentagem da variança que pôde ser prevista pelo modelo de regressão e, portanto, nos diz o quão “próximo” as medidas reais estão do nosso modelo.

O valor do seu R-Quadrado varia de 0 a 1 e geralmente é representado em porcentagem. Por exemplo, um R² = 75% nos diz que 75% da variância de nossos dados podem ser explicados pelo modelo construído, enquanto os outros 25%, teoricamente, se tratariam de uma variância residual.

### Erro Absoluto Médio (MAE)

O Erro Absoluto Médio consiste na média das distâncias entre valores preditos e reais. Em outras palavras, tira-se média da diferença absoluta dos valores preditos e real.

In [ ]:
# No exemplo abaixo vamos ver o MSE do algoritmo XGB, pois no loop for foi o último a ser executado, na matemática fica assim:
(abs(y_test - result).sum() / len(result))

### Erro Quadrático Médio (MSE)

O Erro Quadrático Médio consiste na média do erro das previsões ao quadrado. Em outras palavras, é a média da soma dos resíduos(diferença entra os valores predito e real) ao quadrado.

In [ ]:
# No exemplo abaixo vamos ver o MSE do algoritmo XGB, pois no loop for foi o último a ser executado, na matemática fica assim:
((y_test - result)**2).sum() / len(result)

--------------------------------------------

### Melhor resultado do modelo:

RandomForest: R^2 = 0.510800 | MAE = 430.662239